---
# Source: lotus/templates/controller-rbac.yaml

kind: ServiceAccount
apiVersion: v1
metadata:
  name: lotus-controller
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lotus-controller
  namespace: default
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - pods
      - deployments
      - statefulsets
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - "lotus.lotusload.com"
    resources:
      - lotuses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lotus-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lotus-controller
subjects:
- kind: ServiceAccount
  name: lotus-controller
  namespace: default