/*

Generated by using code-generator

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nghialv/lotus/pkg/app/lotus/client/clientset/versioned/typed/lotus/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeLotusV1beta1 struct {
	*testing.Fake
}

func (c *FakeLotusV1beta1) Lotuses(namespace string) v1beta1.LotusInterface {
	return &FakeLotuses{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeLotusV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
