---
# Source: lotus/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lotuses.lotus.lotusload.com
spec:
  group: lotus.lotusload.com
  version: v1beta1
  scope: Namespaced
  names:
    kind: Lotus
    plural: lotuses
    singular: lotus
    categories:
      - all
  additionalPrinterColumns:
    - name: Phase
      type: string
      description: The current phase of Lotus
      JSONPath: .status.phase
    - name: WorkerReplicas
      type: integer
      description: The number of workers launched for this Lotus
      JSONPath: .spec.worker.replicas
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - worker
        status:
          properties:
            phase:
              type: string
              enum:
              - "Pending"
              - "Preparing"
              - "Running"
              - "Cleaning"
              - "FailureCleaning"
              - "Succeeded"
              - "Failed"
