{
 "title": "GRPC",
 "tags": [ "grpc" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testId",
    "label": "TestID",
    "query": "query_result(count by(job) (count_over_time(up[$__range])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (up{job=~\"$testId-worker\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Number of virtual users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (virtual_user_status) (lotus_virtual_user_count{job=~\"$testId-worker\"})",
     "legendFormat": "virtual_user_status"
    }
   ]
  },
  {
   "title": "RPCs / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lotus_grpc_client_completed_rpcs_per_second:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ grpc_client_method }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "lotus_grpc_client_roundtrip_latency:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ grpc_client_method }}"
    }
   ]
  },
  {
   "title": "RPCs / seconds grouping by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lotus_grpc_client_completed_rpcs_per_second:status{job=~\"$testId-worker\"}",
     "legendFormat": "{{ grpc_client_status }}"
    }
   ]
  },
  {
   "title": "Percentage of failed RPCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "lotus_grpc_client_completed_rpcs_failure_percentage:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ grpc_client_method }}"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_grpc_client_sent_bytes_per_rpc:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ grpc_client_method }}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_grpc_client_received_bytes_per_rpc:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ grpc_client_method }}"
    }
   ]
  }
 ]
}
{
 "title": "HTTP",
 "tags": [ "http" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testId",
    "label": "TestID",
    "query": "query_result(count by(job) (count_over_time(up[$__range])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (up{job=~\"$testId-worker\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Number of virtual users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (virtual_user_status) (lotus_virtual_user_count{job=~\"$testId-worker\"})",
     "legendFormat": "virtual_user_status"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lotus_http_client_completed_requests_per_second:host:route:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ http_client_method }}/{{ http_client_host }}{{ http_client_route }}"
    }
   ]
  },
  {
   "title": "Percentage of 5xx Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "lotus_http_client_completed_requests_5xx_percentage:host:route:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ http_client_method }}/{{ http_client_host }}{{ http_client_route }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "lotus_http_client_roundtrip_latency:host:route:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ http_client_method }}/{{ http_client_host }}{{ http_client_route }}"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_http_client_sent_bytes:host:route:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ http_client_method }}/{{ http_client_host }}{{ http_client_route }}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_http_client_received_bytes:host:route:method{job=~\"$testId-worker\"}",
     "legendFormat": "{{ http_client_method }}/{{ http_client_host }}{{ http_client_route }}"
    }
   ]
  }
 ]
}