/*

Generated by using code-generator

*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	lotusv1beta1 "github.com/nghialv/lotus/pkg/app/lotus/client/clientset/versioned/typed/lotus/v1beta1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	LotusV1beta1() lotusv1beta1.LotusV1beta1Interface
	// Deprecated: please explicitly pick a version if possible.
	Lotus() lotusv1beta1.LotusV1beta1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	lotusV1beta1 *lotusv1beta1.LotusV1beta1Client
}

// LotusV1beta1 retrieves the LotusV1beta1Client
func (c *Clientset) LotusV1beta1() lotusv1beta1.LotusV1beta1Interface {
	return c.lotusV1beta1
}

// Deprecated: Lotus retrieves the default version of LotusClient.
// Please explicitly pick a version.
func (c *Clientset) Lotus() lotusv1beta1.LotusV1beta1Interface {
	return c.lotusV1beta1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.lotusV1beta1, err = lotusv1beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.lotusV1beta1 = lotusv1beta1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.lotusV1beta1 = lotusv1beta1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
