/*

Generated by using code-generator

*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/nghialv/lotus/pkg/app/lotus/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Lotuses returns a LotusInformer.
	Lotuses() LotusInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Lotuses returns a LotusInformer.
func (v *version) Lotuses() LotusInformer {
	return &lotusInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
