/*

Generated by using code-generator

*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// LotusListerExpansion allows custom methods to be added to
// LotusLister.
type LotusListerExpansion interface{}

// LotusNamespaceListerExpansion allows custom methods to be added to
// LotusNamespaceLister.
type LotusNamespaceListerExpansion interface{}
