/*

Generated by using code-generator

*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/nghialv/lotus/pkg/app/lotus/apis/lotus/v1beta1"
	scheme "github.com/nghialv/lotus/pkg/app/lotus/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LotusesGetter has a method to return a LotusInterface.
// A group's client should implement this interface.
type LotusesGetter interface {
	Lotuses(namespace string) LotusInterface
}

// LotusInterface has methods to work with Lotus resources.
type LotusInterface interface {
	Create(*v1beta1.Lotus) (*v1beta1.Lotus, error)
	Update(*v1beta1.Lotus) (*v1beta1.Lotus, error)
	UpdateStatus(*v1beta1.Lotus) (*v1beta1.Lotus, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Lotus, error)
	List(opts v1.ListOptions) (*v1beta1.LotusList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Lotus, err error)
	LotusExpansion
}

// lotuses implements LotusInterface
type lotuses struct {
	client rest.Interface
	ns     string
}

// newLotuses returns a Lotuses
func newLotuses(c *LotusV1beta1Client, namespace string) *lotuses {
	return &lotuses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the lotus, and returns the corresponding lotus object, and an error if there is any.
func (c *lotuses) Get(name string, options v1.GetOptions) (result *v1beta1.Lotus, err error) {
	result = &v1beta1.Lotus{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lotuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Lotuses that match those selectors.
func (c *lotuses) List(opts v1.ListOptions) (result *v1beta1.LotusList, err error) {
	result = &v1beta1.LotusList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lotuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested lotuses.
func (c *lotuses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("lotuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a lotus and creates it.  Returns the server's representation of the lotus, and an error, if there is any.
func (c *lotuses) Create(lotus *v1beta1.Lotus) (result *v1beta1.Lotus, err error) {
	result = &v1beta1.Lotus{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("lotuses").
		Body(lotus).
		Do().
		Into(result)
	return
}

// Update takes the representation of a lotus and updates it. Returns the server's representation of the lotus, and an error, if there is any.
func (c *lotuses) Update(lotus *v1beta1.Lotus) (result *v1beta1.Lotus, err error) {
	result = &v1beta1.Lotus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("lotuses").
		Name(lotus.Name).
		Body(lotus).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *lotuses) UpdateStatus(lotus *v1beta1.Lotus) (result *v1beta1.Lotus, err error) {
	result = &v1beta1.Lotus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("lotuses").
		Name(lotus.Name).
		SubResource("status").
		Body(lotus).
		Do().
		Into(result)
	return
}

// Delete takes name of the lotus and deletes it. Returns an error if one occurs.
func (c *lotuses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lotuses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *lotuses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lotuses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched lotus.
func (c *lotuses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Lotus, err error) {
	result = &v1beta1.Lotus{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("lotuses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
